### ISSUE TITLE
Please upload v0.1.2 to Maven Central

### ISSUE THREAD

**Issue by cohei** [airbrake/logback#14]
https://mvnrepository.com/artifact/io.airbrake/logback

Hi,

I think v0.1.2 is not available because it's not on Maven Central.

fixes: #9 https://github.com/airbrake/logback/issues/12#issuecomment-1379751958

**Comment by thibaut-wed** [comment]
Hello @airbrake,

Do you have any plan to release this library version on Maven Central as asked in the previous comment?
Currently airbrake-logback is unusable on Java 17.

Thanks

**Comment by luisgsotoaboal** [comment]
Hi 👋 

I was doing some tests yesterday and it turns out **airbrake-logback v0.1.1** is not compatible, not just with JDK 17, but also with any of the **airbrake-javabrake** **0.2.x** nor **0.3.0** versions released in the last **five** years, because **airbrake-logback v0.1.1** is [using](https://github.com/airbrake/logback/blob/4d435fa721a6bff20ec518f0387ef05deb74f5a5/src/main/java/AirbrakeAppender.java#L43) a `Notifier(int, String)` constructor that was [removed from **airbrake-javabrake** in March 2021](https://github.com/airbrake/javabrake/commit/5f08090b6046629822d70297f7613d07fea2d27b) in favor of the current `Notifier(Config)` constructor:
```
Caused by: java.lang.NoSuchMethodError: 'void io.airbrake.javabrake.Notifier.<init>(int, java.lang.String)'
        at      at io.airbrake.logback.AirbrakeAppender.initNotifier(AirbrakeAppender.java:43)
        at      at io.airbrake.logback.AirbrakeAppender.setProjectKey(AirbrakeAppender.java:32)
```
This forces me to use **airbrake-javabrake v0.1.6** which as I said is more than 5 years old, and I don't even know if it's still fully compatible with Airbrake's current API.

All of this is of course solved in **airbrake-logback v0.1.2** (that's why I'm writing a comment here instead of opening a new issue). Even the [README](https://github.com/airbrake/logback#readme) tells us to use **v0.1.2** but, as @thibaut-wed and @cohei mentioned, **v0.1.2** is not available on Maven so we cannot use it.

We are getting some pressure to just switch to **airbrake-log4javabrake2** which AFAIK doesn't suffer from any of this problems, but we'd really like to stay with Logback as that's what we use in most of our services.

We would really appreciate it if you could just release **v0.1.2** to Maven Central. Thanks in advance.


---

PS: tagging @sumitjoshi1989 as v0.1.2 committer, @mmcdaris as v0.1.2 reviewer and approver, and @thompiler as the one who deleted the already-merged `logback_v0.1.2` branch barely 11 hours ago. Sorry for bothering you, guys, I just hope one of you is able to solve this. Thanks!

**Comment by luisgsotoaboal** [comment]
@cohei It also fixes https://github.com/airbrake/logback/issues/9, you may want to include that one too in your original message.

**Comment by cohei** [comment]
OK, I'll add it.

**Comment by mmcdaris** [comment]
Apologies for the delay on this one. The release slipped through the cracks. We now see v0.1.2 live on mvn repository.
Please let us know if you have any further issues. Closing this one out.

**Comment by luisgsotoaboal** [comment]
Thanks a lot!
